apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  namespace: production-env
spec:
  replicas: 1  #how many pods can be acquired by the replicaset (autoscaling group) 
  selector:
    matchLabels:
      app: app-web

  template:
    metadata:
      labels:
        app: app-web

    spec:
      imagePullSecrets:
      - name: eks-docker #JFrog-Cred
      containers:
      - name:  app-web
        image: queenslandm.jfrog.io/tweet-trend-new-docker-local/ttrend:2.1.2
        imagePullPolicy: Always
        ports: 
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"