apiVersion: v1
kind: Service
metadata:
  name: app-web-service
  namespace: production-env

spec:
  type: NodePort
  selector:
    app: app-web
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000